// Mocks generated by Mockito 5.4.6 from annotations
// in budgets/test/features/transactions/domain/providers/paginated_expenses_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:budgets/core/enums/transaction_type.dart' as _i5;
import 'package:budgets/features/transactions/data/datasource/transaction_api.dart'
    as _i2;
import 'package:budgets/features/transactions/domain/model/transaction_model.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePaginatedTransactions_0 extends _i1.SmartFake
    implements _i2.PaginatedTransactions {
  _FakePaginatedTransactions_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TransactionsApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionsApi extends _i1.Mock implements _i2.TransactionsApi {
  MockTransactionsApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.TransactionModel>> getTransactions() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactions,
          [],
        ),
        returnValue: _i3.Future<List<_i4.TransactionModel>>.value(
            <_i4.TransactionModel>[]),
      ) as _i3.Future<List<_i4.TransactionModel>>);

  @override
  _i3.Future<_i2.PaginatedTransactions> getTransactionsPaginated({
    int? page = 0,
    int? limit = 10,
    _i5.TransactionType? type,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactionsPaginated,
          [],
          {
            #page: page,
            #limit: limit,
            #type: type,
          },
        ),
        returnValue: _i3.Future<_i2.PaginatedTransactions>.value(
            _FakePaginatedTransactions_0(
          this,
          Invocation.method(
            #getTransactionsPaginated,
            [],
            {
              #page: page,
              #limit: limit,
              #type: type,
            },
          ),
        )),
      ) as _i3.Future<_i2.PaginatedTransactions>);

  @override
  _i3.Future<void> addTransaction(
    String? amount,
    String? description,
    String? categoryName,
    Map<String, String>? subcategoryAmounts,
    _i5.TransactionType? transactionType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTransaction,
          [
            amount,
            description,
            categoryName,
            subcategoryAmounts,
            transactionType,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
